name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.GRASS_USER }}
          password: ${{ secrets.GRASS_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.GRASS_USER }}/diggrass:latest
            

                    
