name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.GRASS_USER }}
          password: ${{ vars.GRASS_PASS }} 
      - name: Build the Docker image
        run: docker build --file ./Dockerfile -t ${{ secrets.GRASS_USER }}/diggrass:latest .
      - name: Docker image push
        run: docker push ${{ secrets.GRASS_USER }}/diggrass:latest
            

                    
